---01---

ALTER TABLE HR.EMPLOYEES ADD MAX_SALARY NUMBER;

SELECT * FROM HR.EMPLOYEES;

UPDATE HR.EMPLOYEES SET MAX_SALARY=(SELECT MAX(SALARY) FROM HR.EMPLOYEES);

DELETE FROM HR.EMPLOYEES WHERE SALARY=(SELECT MIN(SALARY) FROM HR.EMPLOYEES);

--2--

CREATE INDEX DPR_NAME_IDX
ON HR.DEPARTMENTS (DEPARTMENT_NAME);

DROP INDEX DPR_NAME_IDX 
ON HR.DEPARTMENTS(DEPARTMENT_NAME);

Define index (named DPR_NAME_IDX) on DEPARTMENT_NAME column of DEPARTMENTS
table.
Create a table from EMPLOYEES with distinct department_id column. Add
department_name to that table. With DEPARTMENTS table, update department_name for included
department_ids and insert department_id and department_name values for not included rows. Use
MERGE keywor++



---02---

CREATE INDEX DPR_NAME_IDX
ON HR.DEPARTMENTS (DEPARTMENT_NAME);

ALTER TABLE HR.EMPLOYEES
ADD CONSTRAINT CNSTR_SALARY
CHECK (SALARY BETWEEN 1000 AND 100000);

DROP INDEX DPR_NAME_IDX;

ALTER TABLE HR.EMPLOYEES
DISABLE CONSTRAINT CNSTR_SALARY;

ALTER TABLE HR.EMPLOYEES
ENABLE CONSTRAINT CNSTR_SALARY;

ALTER TABLE HR.EMPLOYEES DROP CONSTRAINT CNSTR_SALARY;

---3---

CREATE TABLE INFOS AS(SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS);

ALTER TABLE INFOS ADD DEP_NAME varchar2(45);

INSERT INTO INFOS(DEP_NAME)SELECT DEPARTMENT_NAME FROM HR.DEPARTMENTS;

MERGE INTO INFOS i USING(SELECT DEPARTMENT_ID,DEPARTMENT_NAME FROM HR.DEPARTMENTS d) 
ON (i.DEPARTMENT_ID = d.DEPARTMENT_ID) ;

---4---

SELECT FIRST_NAME, LAST_NAME,JOB_ID,DEPARTMENT_ID,SALARY
FROM HR.EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM HR.EMPLOYEES);
WITH J_TITLE AS (
SELECT JOB_TITLE FROM HR.JOBS ;
WITH D_NAME AS(
SELECT DEPARTMENT_NAME FROM HR.DEPARTMENTS;
WITH FULL_NAME AS(
SELECT CONCAT(CONCAT(FIRST_NAME, ' '),LAST_NAME) FROM HR.EMPLOYEES;

---5---
/*
EÐER Script'imizin çok fazla hata barýndýrdýðýný düþünüyor ve 
yaptýðý bütün iþleri geri almak istiyorsak ROLLBACK iþlemi yaparýz.

EÐER Script'imizin sorunsuzca çalýþtýðýný düþünüyor ve ilgili
kiþilerin de ulaþmasýný saðlamak istiyorsak COMMIT iþlemi yaparýz.
*/