CREATE OR REPLACE PACKAGE DISPLAY_ALL_NAMES_PACKAGE
IS
PROCEDURE DISPLAY_ALL_NAMES;END DISPLAY_ALL_NAMES_PACKAGE;
CREATE OR REPLACE PACKAGE BODY DISPLAY_ALL_NAMES_PACKAGE
IS PROCEDURE display_all_employee_names IS 
BEGIN
FOR employee IN(SELECT first_name FROM HR.EMPLOYEES)
LOOP DBMS_OUTPUT.PUT_LINE(employee.first_name);
END LOOP ;   
END;
BEGIN	
DBMS_OUTPUT.PUT_LINE('DISPLAY_NAME_PACKAGE');
END DISPLAY_ALL_NAMES_PACKAGE;
BEGIN 
DISPLAY_ALL_NAMES_PACKAGE.DISPLAY_ALL_NAMES;
END;

